package servlet;
/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'yang' at '16-7-30 下午6:41' with Gradle 2.14.1
 *
 * @author yang, @date 16-7-30 下午6:41
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
